# Custom Language File for Launcher Customizer

[ejs.app]
title = "Lunaiz Launcher"

[ejs.landing]
mediaLinkURL = "https://lunaiz.com/"
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/jbJfEqvNdu"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "https://discord.gg/FdFx3B4vky"

[ejs.welcome]
welcomeHeader = "Lunaiz Launcher"
welcomeDescription = "Lunaiz 서버를 접속하기 위한 수단입니다. 재밌게 즐겨주셨으면 합니다."
welcomeDescCTA = "루나이즈을 사랑하는 당신을 위한 최고의 선물이 되겠습니다."
